more curl

diff --git a/api/argo-templates/ncn/worker.drain.yaml b/api/argo-templates/ncn/worker.drain.yaml
--- a/api/argo-templates/ncn/worker.drain.yaml
+++ b/api/argo-templates/ncn/worker.drain.yaml
@@ -25,7 +25,7 @@
 tasks:
   - name: wait-for-cfs
     templateRef:
-      name: ssh-template
+      name: kubectl-and-curl-template
       template: shell-script
     arguments:
       parameters:
@@ -33,9 +33,27 @@ tasks:
           value: "{{ `{{inputs.parameters.dryRun}}` }}"
         - name: scriptContent
           value: |
-            /usr/share/doc/csm/upgrade/1.2/scripts/cfs/wait_for_configuration.sh \
-              --xnames \
-              $(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ `{{inputs.parameters.targetNcn}}` }} 'cat /etc/cray/xname')
+            TARGET_NCN={{ `{{inputs.parameters.targetNcn}}` }}
+            TARGET_XNAME=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/sls/v1/search/hardware?extra_properties.Role=Management" | \
+                jq -r ".[] | select(.ExtraProperties.Aliases[] | contains(\"$TARGET_NCN\")) | .Xname")
+
+            while true; do
+              RESULT=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=pending" | jq length)
+              if [[ "$RESULT" -eq 0 ]]; then
+                break
+              fi
+              echo "Waiting for configuration to complete.  ${RESULT} components remaining."
+              sleep 30
+            done
+
+            CONFIGURED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=configured" | jq length)
+            FAILED=$(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=failed" | jq length)
+            echo "Configuration complete. $CONFIGURED component(s) completed successfully.  $FAILED component(s) failed."
+            if [ "$FAILED" -ne "0" ]; then
+              echo "The following components failed: $(curl -s -k -H "Authorization: Bearer ${TOKEN}" "https://api-gw-service-nmn.local/apis/cfs/v2/components?ids=${TARGET_XNAME}&status=failed"  | jq -r '. | map(.id) | join(",")')"
+              exit 1
+            fi
+            
   - name: ensure-etcd-pods
     templateRef:
       name: ssh-template
